'use strict';
const http      = require('http');
const Koa       = require('koa');
const app       = new Koa();
const router    = require('./router/index');
const bodyParser = require('koa-bodyparser');
require('./config/db');
app.use(bodyParser());
app.use(router.routes());
app.use(router.allowedMethods());
http.createServer(app.callback()).listen(3000);